package com.gallang.compiler;

import java.util.*;

/**
 * Emits a GALasm-compatible .pld file from a CompiledProgram.
 *
 * GAL22V10 pin layout (24 pins):
 *   Row 1 (left→right): pins  1-12
 *   Row 2 (left→right): pins 13-24
 *   Pin 12 = GND, Pin 24 = VCC (always fixed).
 */
public class PldEmitter {

    private static final int GND_PIN = 12;
    private static final int VCC_PIN = 24;

    public static String emit(LogicCompiler.CompiledProgram prog) {
        StringBuilder sb = new StringBuilder();

        sb.append("GAL22V10\n");
        sb.append(prog.deviceName).append("\n\n");

        sb.append(buildPinRow(prog.pinMap, 1,  12)).append("\n");
        sb.append(buildPinRow(prog.pinMap, 13, 24)).append("\n\n");

        for (LogicCompiler.CompiledEquation eq : prog.equations) {
            String lhs = eq.registered ? eq.signal + ".R" : eq.signal;
            sb.append(lhs)
              .append(" = ")
              .append(eq.expr.toGalasm())
              .append("\n");
        }

        sb.append("\n\nDESCRIPTION\n");
        sb.append("Generated by gallang compiler\n");

        return sb.toString();
    }

    private static String buildPinRow(Map<Integer, String> pinMap, int from, int to) {
        List<String> names = new ArrayList<>();
        for (int pin = from; pin <= to; pin++) {
            if (pin == GND_PIN)       names.add("GND");
            else if (pin == VCC_PIN)  names.add("VCC");
            else if (pinMap.containsKey(pin)) names.add(pinMap.get(pin));
            else                      names.add("NC");
        }
        return String.join(" ", names);
    }
}
